import { FeatureModuleMeta } from '../types';

export const FEATURE_MODULE_REGISTRY: FeatureModuleMeta[] = [
  {
    id: 'landing',
    name: 'Landing Experience',
    description: 'Cinematic landing experience introducing Personal Gemini Journal.',
    status: 'stage_ready',
    cssFile: 'src/features/landing/landing.css',
    securityScope: 'Public Shell / Gateway',
  },
  {
    id: 'authentication',
    name: 'Firebase Auth & User Isolation',
    description: 'Firebase Authentication with strict /users/{uid} isolation boundary.',
    status: 'foundation_ready',
    cssFile: 'src/features/authentication/auth.css',
    securityScope: 'Identity & Access Control',
  },
  {
    id: 'dashboard',
    name: 'Personal Life Dashboard',
    description: 'Unified hub for journals, mood, goals, books, and memories.',
    status: 'foundation_ready',
    cssFile: 'src/features/dashboard/dashboard.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'journal',
    name: 'Journal & Rich Editor',
    description: 'Rich text editor, voice-to-text, images, bookmarks, and PIN lock.',
    status: 'foundation_ready',
    cssFile: 'src/features/journal/journal.css',
    securityScope: 'User Encrypted / PIN Guarded',
  },
  {
    id: 'ask-my-journal',
    name: 'Ask My Journal',
    description: 'ChatGPT-like interface grounded in user historical data.',
    status: 'foundation_ready',
    cssFile: 'src/features/ask-my-journal/ask-my-journal.css',
    securityScope: 'Server-Side Gemini Proxied',
  },
  {
    id: 'goals',
    name: 'Goal Journey Map',
    description: 'Visual map-style journey with sequential milestones and completion times.',
    status: 'foundation_ready',
    cssFile: 'src/features/goals/goals.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'memories',
    name: '3D Memories Carousel',
    description: 'Spatial 3D carousel aggregating journals, goals, books, and music.',
    status: 'foundation_ready',
    cssFile: 'src/features/memories/memories.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'mood',
    name: 'Mood Journey Tracker',
    description: 'Timeline tracking Mood, Stress, Energy, and Confidence metrics.',
    status: 'foundation_ready',
    cssFile: 'src/features/mood/mood.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'library',
    name: 'Digital Books Library',
    description: 'Book reading progress, ratings, quotes, and AI book insights.',
    status: 'foundation_ready',
    cssFile: 'src/features/library/library.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'music',
    name: 'Music Memories',
    description: 'Songs, albums, mood associations, and memory timeline.',
    status: 'foundation_ready',
    cssFile: 'src/features/music/music.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'calendar',
    name: 'Calendar & Tasks',
    description: 'Events, tasks, dates, times, months, years, and attachments.',
    status: 'foundation_ready',
    cssFile: 'src/features/calendar/calendar.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'notifications',
    name: 'Scheduled Reminders',
    description: 'Scheduled alerts, reminder history, and sequential presentation.',
    status: 'foundation_ready',
    cssFile: 'src/features/notifications/notifications.css',
    securityScope: 'Authenticated User Only',
  },
  {
    id: 'motivation',
    name: 'Daily Motivation',
    description: 'Daily inspirational quotes by category with refined animations.',
    status: 'foundation_ready',
    cssFile: 'src/features/motivation/motivation.css',
    securityScope: 'Public / Personalized',
  },
  {
    id: 'assistant',
    name: 'Personal AI Assistant',
    description: 'Multi-turn conversational AI with analysis and insights.',
    status: 'foundation_ready',
    cssFile: 'src/features/assistant/assistant.css',
    securityScope: 'Server-Side Gemini Proxied',
  },
];
